import 'package:quotes_cat_api_sqlite/models/category_model.dart';

class Data {
  static List<CategoryModel> catList = [
    CategoryModel(id: 1, catName: "age", catImg: "age"),
    CategoryModel(id: 2, catName: "alone", catImg: "alone"),
    CategoryModel(id: 3, catName: "amazing", catImg: "amazing"),
    CategoryModel(id: 4, catName: "anger", catImg: "success"),
    CategoryModel(id: 5, catName: "architecture", catImg: "success"),
    CategoryModel(id: 6, catName: "art", catImg: "success"),
    CategoryModel(id: 7, catName: "attitude", catImg: "success"),
    CategoryModel(id: 8, catName: "beauty", catImg: "success"),
    CategoryModel(id: 9, catName: "best", catImg: "success"),
    CategoryModel(id: 10, catName: "birthday", catImg: "success"),
    CategoryModel(id: 11, catName: "business", catImg: "success"),
    CategoryModel(id: 12, catName: "car", catImg: "success"),
    CategoryModel(id: 13, catName: "change", catImg: "success"),
    CategoryModel(id: 14, catName: "communication", catImg: "success"),
    CategoryModel(id: 15, catName: "computers", catImg: "success"),
    CategoryModel(id: 16, catName: "cool", catImg: "success"),
    CategoryModel(id: 17, catName: "courage", catImg: "success"),
    CategoryModel(id: 18, catName: "dad", catImg: "success"),
    CategoryModel(id: 19, catName: "dating", catImg: "success"),
    CategoryModel(id: 20, catName: "death", catImg: "success"),
    CategoryModel(id: 21, catName: "design", catImg: "success"),
    CategoryModel(id: 22, catName: "dreams", catImg: "success"),
    CategoryModel(id: 23, catName: "education", catImg: "success"),
    CategoryModel(id: 24, catName: "environmental", catImg: "success"),
    CategoryModel(id: 25, catName: "equality", catImg: "success"),
    CategoryModel(id: 26, catName: "experience", catImg: "success"),
    CategoryModel(id: 27, catName: "failure", catImg: "success"),
    CategoryModel(id: 28, catName: "faith", catImg: "success"),
    CategoryModel(id: 29, catName: "family", catImg: "success"),
    CategoryModel(id: 30, catName: "famous", catImg: "success"),
    CategoryModel(id: 31, catName: "fear", catImg: "success"),
    CategoryModel(id: 32, catName: "fitness", catImg: "success"),
    CategoryModel(id: 33, catName: "food", catImg: "success"),
    CategoryModel(id: 34, catName: "forgiveness", catImg: "success"),
    CategoryModel(id: 35, catName: "freedom", catImg: "success"),
    CategoryModel(id: 36, catName: "friendship", catImg: "success"),
  ];
}
